# ---------------------------------------------------------------------------
# Backward-compatibility shim — do not edit this file.
#
# The canonical implementations have moved to the neat_plots package:
#   neat_plots/manhattan_plot.py  →  ManhattanPlot
#   neat_plots/boroughs_plot.py   →  BoroughsPlot
#
# This shim lets existing scripts (and conda-develop installs) that do:
#
#   from manhattan_plot import ManhattanPlot
#
# continue to work without any changes.
#
# The full legacy source is preserved in git history (commit before this one).
# ---------------------------------------------------------------------------

from neat_plots.manhattan_plot import ManhattanPlot  # noqa: F401
from neat_plots.boroughs_plot  import BoroughsPlot   # noqa: F401

__all__ = ["ManhattanPlot", "BoroughsPlot"]
