"""
Integration tests using a realistic synthetic chr22 GWAS dataset.

The fixture file (chr22_synthetic_gwas.tsv.gz, ~233 KB) was generated by
tests/integration/generate_fixture.py and committed to the repository.
It contains 10,000 variants on chromosome 22 with:
  - Three genome-wide-significant loci (P < 5e-8)
  - Realistic LD-block structure around each signal
  - BETA, SE, MAF columns for extended plots
  - Mild genomic inflation (λ ≈ 1.05)

These tests mirror the real-world usage patterns from the example scripts
(make_manhattan_qq_plots.py, make_exwas_meta_singles_plots.py).
"""

from __future__ import annotations

import os
import pathlib

import numpy as np
import pandas as pd
import pytest

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from neat_plots import ManhattanPlot

# ---------------------------------------------------------------------------
# Fixture path
# ---------------------------------------------------------------------------

DATA_DIR  = pathlib.Path(__file__).parent
GWAS_FILE = DATA_DIR / "chr22_synthetic_gwas.tsv.gz"


@pytest.fixture(autouse=True)
def close_figures():
    yield
    plt.close("all")


@pytest.fixture(scope="module")
def mp_prepared():
    """
    Single ManhattanPlot instance, fully prepared, reused across all tests
    in this module (scope='module') to avoid re-loading 10k rows repeatedly.
    """
    mp = ManhattanPlot(str(GWAS_FILE), title="Chr22 Synthetic GWAS")
    mp.prepare()
    return mp


# ---------------------------------------------------------------------------
# Data-loading integrity
# ---------------------------------------------------------------------------


class TestDataIntegrity:
    def test_file_exists(self):
        assert GWAS_FILE.exists(), (
            f"Integration fixture not found: {GWAS_FILE}\n"
            "Run tests/integration/generate_fixture.py to regenerate."
        )

    def test_row_count(self, mp_prepared):
        assert len(mp_prepared.df) == 10_000

    def test_single_chromosome(self, mp_prepared):
        assert set(mp_prepared.df["#CHROM"]) == {22}

    def test_no_zero_p(self, mp_prepared):
        assert (mp_prepared.df["P"].dropna() > 0).all()

    def test_thinning_reduces_rows(self, mp_prepared):
        assert len(mp_prepared.thinned) < len(mp_prepared.df)

    def test_significant_hits_present(self, mp_prepared):
        n_sig = (mp_prepared.thinned["P"] < 5e-8).sum()
        assert n_sig > 0, "Expected at least one GWS hit in the thinned data"

    def test_extra_columns_retained(self, mp_prepared):
        """BETA, SE, MAF should survive load → clean → thin."""
        for col in ("BETA", "SE", "MAF"):
            assert col in mp_prepared.df.columns


# ---------------------------------------------------------------------------
# Standard GWAS workflow (mirrors make_manhattan_qq_plots.py)
# ---------------------------------------------------------------------------


class TestStandardWorkflow:
    def test_prepare_pipeline(self):
        """Full prepare() call completes without error."""
        mp = ManhattanPlot(str(GWAS_FILE))
        mp.prepare()
        assert mp.thinned is not None

    def test_prepare_chunked_matches_standard(self):
        """Chunked and standard pipelines produce the same thinned count."""
        mp_std   = ManhattanPlot(str(GWAS_FILE))
        mp_chunk = ManhattanPlot(str(GWAS_FILE))
        mp_std.prepare()
        mp_chunk.prepare(chunked=True, chunksize=2_000)
        assert len(mp_std.thinned) == len(mp_chunk.thinned)

    def test_full_plot_horizontal(self, tmp_path):
        mp = ManhattanPlot(str(GWAS_FILE), title="Chr22 Horizontal")
        mp.prepare()
        mp.update_plotting_parameters(vertical=False, sig=5e-8, merge_genes=True)
        out = str(tmp_path / "chr22_horizontal.png")
        mp.full_plot(save=out)
        assert os.path.exists(out)

    def test_full_plot_vertical(self, tmp_path):
        mp = ManhattanPlot(str(GWAS_FILE), title="Chr22 Vertical")
        mp.prepare()
        mp.update_plotting_parameters(vertical=True, sig=5e-8)
        out = str(tmp_path / "chr22_vertical.png")
        mp.full_plot(save=out)
        assert os.path.exists(out)

    def test_full_plot_no_table(self, tmp_path):
        mp = ManhattanPlot(str(GWAS_FILE))
        mp.prepare()
        mp.update_plotting_parameters(vertical=False)
        out = str(tmp_path / "chr22_no_table.png")
        mp.full_plot(save=out, with_table=False)
        assert os.path.exists(out)

    def test_qq_plot_saved(self, tmp_path):
        mp = ManhattanPlot(str(GWAS_FILE))
        mp.prepare()
        out = str(tmp_path / "chr22_qq.png")
        mp.qq_plot(save=out)
        assert os.path.exists(out)
        assert os.path.exists(out.replace(".png", ".csv"))

    def test_qq_lambda_gc_reasonable(self, capsys):
        mp = ManhattanPlot(str(GWAS_FILE))
        mp.prepare()
        mp.qq_plot()
        out = capsys.readouterr().out
        # Extract lambda value from output
        for line in out.splitlines():
            if "Lambda GC" in line:
                lam = float(line.split(":")[-1].strip())
                assert 0.9 < lam < 1.5, f"λ={lam} is outside expected range [0.9, 1.5]"
                break


# ---------------------------------------------------------------------------
# ExWAS singles workflow (mirrors make_exwas_meta_singles_plots.py)
# ---------------------------------------------------------------------------


class TestExwasWorkflow:
    def test_dynamic_p_threshold(self):
        """
        Mirrors the ExWAS pattern: compute a Bonferroni threshold from
        the number of tests and pass it as `sig`.
        """
        mp = ManhattanPlot(str(GWAS_FILE))
        mp.prepare()
        n_tests      = len(mp.df)
        bonferroni   = 0.05 / n_tests
        mp.update_plotting_parameters(sig=bonferroni, sug=bonferroni * 10)
        # Check threshold is set correctly
        assert abs(mp.sig - bonferroni) < 1e-20

    def test_col_map_rename(self, tmp_path):
        """Rename columns on load (common in ExWAS / non-standard files)."""
        # Write a version with non-standard column names
        df = pd.read_csv(GWAS_FILE, sep="\t", compression="gzip")
        df = df.rename(columns={"#CHROM": "CHR", "POS": "BP", "ID": "SNP"})
        alt_path = str(tmp_path / "chr22_altcols.tsv")
        df.to_csv(alt_path, sep="\t", index=False)

        mp = ManhattanPlot(alt_path)
        mp.prepare(col_map={"CHR": "#CHROM", "BP": "POS", "SNP": "ID"})
        assert len(mp.thinned) > 0
        assert "#CHROM" in mp.df.columns

    def test_logp_input(self, tmp_path):
        """Files with pre-computed -log10(P) instead of raw P."""
        df = pd.read_csv(GWAS_FILE, sep="\t", compression="gzip")
        df["LOG10_P"] = -np.log10(df["P"])
        df = df.drop(columns="P")
        lp_path = str(tmp_path / "chr22_logp.tsv")
        df.to_csv(lp_path, sep="\t", index=False)

        mp = ManhattanPlot(lp_path)
        mp.prepare(logp="LOG10_P")
        assert "P" in mp.df.columns
        assert (mp.df["P"].dropna() > 0).all()


# ---------------------------------------------------------------------------
# Multi-series QQ (using BETA-split subgroups)
# ---------------------------------------------------------------------------


class TestMultiSeriesQQ:
    def test_qq_with_subgroups(self, mp_prepared, tmp_path):
        """
        Split by effect direction and overlay both series on one QQ plot,
        as a user might do after collecting QQ CSV write-outs.
        """
        pos_p = mp_prepared.df.loc[mp_prepared.df["BETA"] > 0, "P"].dropna()
        neg_p = mp_prepared.df.loc[mp_prepared.df["BETA"] < 0, "P"].dropna()

        out = str(tmp_path / "chr22_qq_multi.png")
        mp_prepared.qq_plot(
            save=out,
            additional_series={"Positive effect": pos_p, "Negative effect": neg_p},
        )
        assert os.path.exists(out)


# ---------------------------------------------------------------------------
# Persistence round-trip
# ---------------------------------------------------------------------------


class TestPersistence:
    def test_pickle_round_trip(self, tmp_path):
        mp = ManhattanPlot(str(GWAS_FILE))
        mp.prepare()
        pkl = str(tmp_path / "thinned.pickle")
        mp.save_thinned_df(pkl, pickle=True)

        # Reload via pickle path
        mp2 = ManhattanPlot(pkl)
        mp2.load_data()
        assert len(mp2.df) == len(mp.thinned)

    def test_csv_round_trip(self, tmp_path):
        mp = ManhattanPlot(str(GWAS_FILE))
        mp.prepare()
        csv_out = str(tmp_path / "thinned.csv")
        mp.save_thinned_df(csv_out, pickle=False)
        loaded = pd.read_csv(csv_out, index_col=0)
        assert len(loaded) == len(mp.thinned)
